export { default as boxIcon } from "./Vector.png";
export { default as searchIcon } from "./Icon.png";
export { default as heroImg1 } from "./Image.png";
export { default as LeftButton } from "./Vector (2).png";
export { default as RightButton } from "./Vector (1).png";
export { default as Kts } from "./KTC Coconut Milk.png";
export { default as Cheeze } from "./Happy Cow Cheeze.png";
export { default as Yogurt } from "./Desi Yogurt.png";
export { default as Butterkist } from "./Butterkist Salted.png";
export { default as Cocktail } from "./Asya Cocktail.png";
export { default as Fresh } from "./6 Fresh and Tasty Eggs.png";
export { default as Cherry } from "./7up Cherry.png";
export { default as Anchor } from "./Images.png";
export { default as ProductsBtnImgToLeft } from "./Vector (3).png";
export { default as ProductsBtnImgToRight } from "./Next.png";
export { default as Tirnoq } from "./Icon (1).png";
export { default as Signature } from "./Signature.png";
export { default as PeopleAndCou } from "./Picture 3.png";
export { default as Cou } from "./Picture 2.png";
export { default as Cou2 } from "./a3fe6e0b23851d0f608b4952031f5c09.jpg";
export { default as ProductFerma } from "./photo_2022-11-14_11-19-21.jpg";
export { default as PartnersKts } from "./KTC-Logo-1-7723 1.png";
export { default as PartnerAnchor } from "./Logo 1.png";
export { default as PartnerKoLe } from "./ko-lee-noodles 1.png";
export { default as PartnerWoerle } from "./woerle_logo_298x114 1.png";
export { default as Abstrakt } from "./Abstract.png";
export { default as Abstract2 } from "./Abstract (2).png";
export { default as Abstract1 } from "./Abstract (1).png";
export { default as Abstract3 } from "./Abstract (3).png";
export { default as Mastercard } from "./Mastercard.png";
export { default as Visa } from "./visa-logo.png";
export { default as UnionPay } from "./UnionPay.png";
export { default as ApplePay } from "./ApplePay.png";
export { default as GooglePay } from "./GooglePay.png";
export { default as User1 } from "./Frame 10.png";
export { default as User2 } from "./Frame 10 (1).png";
export { default as PriceRange } from "./Price.png";
export { default as NavigationProduct } from "./Navigation.png";
export { default as PayPal } from "./pngaaa 1.png";
export { default as Empty } from "./empty.png";
